# Generated by Django 5.2.1 on 2025-05-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='imagen_perfil',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telefono',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
